adventureworks_dwh:
  target: dev
  outputs:
    dev:
      type: postgres
      host: warehouse-db
      port: 5432
      user: dwh_user
      password: dwh_password
      dbname: warehouse
      schema: public
      threads: 4
